### ISSUE TITLE
NanoMQ 项目报名参加

### ISSUE THREAD

**Issue by luzizhuo** [bayoss/Hacktoberfest2023#3]
项目名称：NanoMQ

仓库地址：https://github.com/emqx/nanomq

标签：已有

联络人：@luzizhuo

说明：NanoMQ 是于 2021 年初发布的边缘计算开源项目，是面向物联网边缘计算场景的下一代轻量级高性能 MQTT 消息服务器。IoT 时代数据是第一生产力，而边缘则是数据诞生的地方。在边缘复杂的网络环境中对数据进行快速汇聚分发，一个高实时、高吞吐的边缘消息总线至关重要。然而由于产业链条长和各垂直行业的历史原因，使得边缘存在协议碎片化和多种消息模式，而且嵌入式环境的算力和功耗也有严格限制。这些问题都对边缘消息总线提出了新的要求与挑战。NanoMQ 致力于解决这些问题，提供一个能够在边缘端统一数据流动的轻量级高性能消息总线。同时提供极佳的拓展性和可移植性，适配各类嵌入式平台。让分散在边缘的碎片数据能够被轻松管理和获取。

**Comment by node** [comment]
已添加。
