### ISSUE TITLE
Apache Kyuubi

### ISSUE THREAD

**Issue by pan3793** [bayoss/Hacktoberfest2023#8]
项目名称：
Apache Kyuubi

仓库地址：
https://github.com/apache/kyuubi

说明：
Apache Kyuubi is a distributed and multi-tenant gateway to provide serverless SQL on data warehouses and lakehouses.

联系人员:
https://github.com/pan3793

**Comment by node** [comment]
欢迎参加！

还需要一个小步骤即可完成：在项目介绍中，增加 #hacktoberfest 标签。

**Comment by pan3793** [comment]
Thanks, label `hacktoberfest` was added via https://github.com/apache/kyuubi/pull/5342

**Comment by node** [comment]
Added.
